# Generated by Django 2.1.7 on 2019-03-11 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0003_auto_20190308_1038'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'permissions': (('add_cat', 'Can change the status of tasks'), ('del_cat', 'Can remove a task by setting its status as closed'))},
        ),
    ]
