# Generated by Django 2.1.7 on 2019-03-11 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0004_auto_20190311_1047'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'permissions': (('add_cat', 'Pode adicionar uma categoria'), ('del_cat', 'Pode excluir uma categoria'))},
        ),
    ]
