# Generated by Django 2.1.7 on 2019-03-11 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0006_auto_20190311_1053'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'permissions': (('add_cat', 'Can change the status of task'), ('del_cat', 'Can remove a task by setting its status as closed'))},
        ),
    ]
